# Generated by Django 4.2.16 on 2024-09-20 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=5.0, max_digits=3),
            preserve_default=False,
        ),
    ]
